# Leer archivos en Google Colab con pandas y numpy extrabásico. Obtener la mediana

Referencias:
https://stackoverflow.com/questions/48340341/how-to-read-csv-to-dataframe-in-google-colab

---
autor: Roberto Méndez Méndez

Editado: 1 Jul 24

Para poder leer tu archivo utiliza el siguiente código, debes dar el ID de tu archivo. Este ID lo extraés de la dirección URL que obtienes, cuando indicas que quieres compartir el archivo. En este ejemplo
* En nombre del archivo es: datos1.txt
* En mi caso su URL para compartirlo es:

https://drive.google.com/file/d/1CE8N1aV8UTBS-XyR7cQ971o8PvqeGDcL/view?usp=sharing

así el id es: 1CE8N1aV8UTBS-XyR7cQ971o8PvqeGDcL

Al ejecutar el código te pedirá permisos de lectura. Otorga los permiso pertinentes, en particular indica que si puede leer archivos en el menu de opciones que te saldrá si el la primera vez que lo haces.

In [5]:
from google.colab import auth
from pydrive.drive import GoogleDrive
from pydrive.auth import GoogleAuth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

myfile = drive.CreateFile({'id': '1CE8N1aV8UTBS-XyR7cQ971o8PvqeGDcL'})
myfile.GetContentFile('datos1.txt')

Ejemplo de lecturas con Pandas
(debe ejecutar el código anterior)

In [15]:
import pandas as pd
frm = pd.read_csv('datos1.txt', header=None)
print("\n Las primeros cinco renglones son \n ",frm.head())
print("\n Las últimos cinco renglones son \n ",frm.tail())
print("\n Que encabezados de columna tengo: \n",frm.columns)
print("\n Datos estadísticosa básicos:\n\n", frm[0].describe())


 Las primeros cinco renglones son 
      0    1     2
0   1  1.3   0.6
1   2  2.1   0.7
2   3  4.8   0.8
3   4  3.3   0.9
4  34  5.6  23.0

 Las últimos cinco renglones son 
      0     1     2
4  34   5.6  23.0
5  34  45.0  67.0
6   2   4.0   6.0
7  12  98.0  90.0
8  12  34.0  56.0

 Que encabezados de columna tengo: 
 Index([0, 1, 2], dtype='int64')

 Datos estadísticosa básicos:

 count     9.000000
mean     11.555556
std      13.380126
min       1.000000
25%       2.000000
50%       4.000000
75%      12.000000
max      34.000000
Name: 0, dtype: float64


### Leer el archivo con numpy y obtener los datos de una columna en una matriz con numpy

Se espera que el archivo solo tenga datos numéricos


In [ ]:
import numpy as np

datosF = np.loadtxt('datos1.txt', delimiter=",")
print("Los datos dfel archivo son son: \n", datosF)

print("Loas datos en la segunda columna son: ",  datosF[:,1])

### Leer el archivo con  Numpy y sacar la mediana de los datos de una columna

Se espera que el archivo solo tenga datos numéricos



In [9]:
import numpy as np

datosF = np.loadtxt('datos1.txt', delimiter=",")
print("Los datos de archivos  son: \n", datosF)

# Obtener la Mediana
c1 = datosF[:,0]
print("Los datos de la primera columna son: ", c1)
c1.sort()
print("Los datos ordenados de la primera columna son: ", c1)
pos = len(c1) //2

if len(datosF) % 2 == 0:
    mediana = (c1[pos-1] + c1[pos]) / 2
else:
    mediana = c1[pos]

print("La mediana es: ", mediana)



Los datos de archivos  son: 
 [[ 1.   1.3  0.6]
 [ 2.   2.1  0.7]
 [ 3.   4.8  0.8]
 [ 4.   3.3  0.9]
 [34.   5.6 23. ]
 [34.  45.  67. ]
 [ 2.   4.   6. ]
 [12.  98.  90. ]
 [12.  34.  56. ]]
Los datos de la primera columna son:  [ 1.  2.  3.  4. 34. 34.  2. 12. 12.]
Los datos ordenados de la primera columna son:  [ 1.  2.  2.  3.  4. 12. 12. 34. 34.]
La mediana es:  4.0
